export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  FORGOT_PASSWORD: "/forgot-password",
  FORGOT_PASSWORD_VERIFY: "/forgot-password/verify",
  FORGOT_PASSWORD_FORM_RESET: "/forgot-password/reset",
  VERIFY_OTP: "/register/verify",
  PROFILE: "/tai-khoan/ho-so",
  CHANGE_PASSWORD: "/tai-khoan/doi-mat-khau",
  REFERRALS: "/tai-khoan/thanh-vien-gioi-thieu",
  FAVORITES: "/tai-khoan/bds-quan-tam",
  RESET_PASSWORD: "/forgot-password/reset",

  ORGANIZATION: "/co-cau-to-chuc",
  ORGANIZATION_COMPANY: "/co-cau-to-chuc/cong-ty",
  ORGANIZATION_OFFICE: "/co-cau-to-chuc/van-phong",
  ORGANIZATION_BRANCH: "/co-cau-to-chuc/chi-nhanh",
  ORGANIZATION_DEPARTMENT: "/co-cau-to-chuc/phong-ban",
  ORGANIZATION_TEAM: "/co-cau-to-chuc/doi-nhom",
  ORGANIZATION_POSITION: "/co-cau-to-chuc/chuc-vu",
  ORGANIZATION_CHART: "/co-cau-to-chuc/so-do-to-chuc",
  ORGANIZATION_CONFIG: "/co-cau-to-chuc/cau-hinh",
} as const;
